package com.my.shardingdemo.pojo;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table employees
 *
 * @mbg.generated do_not_delete_during_merge 2023-05-06
 */
public class Employees {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.id
     *
     * @mbg.generated 2023-05-06
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   ??
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.name
     *
     * @mbg.generated 2023-05-06
     */
    private String name;

    /**
     * Database Column Remarks:
     *   ??
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.age
     *
     * @mbg.generated 2023-05-06
     */
    private Integer age;

    /**
     * Database Column Remarks:
     *   ??
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.position
     *
     * @mbg.generated 2023-05-06
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.hite_time
     *
     * @mbg.generated 2023-05-06
     */
    private Date hiteTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employees.hire_time
     *
     * @mbg.generated 2023-05-06
     */
    private Date hireTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.id
     *
     * @return the value of employees.id
     *
     * @mbg.generated 2023-05-06
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.id
     *
     * @param id the value for employees.id
     *
     * @mbg.generated 2023-05-06
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.name
     *
     * @return the value of employees.name
     *
     * @mbg.generated 2023-05-06
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.name
     *
     * @param name the value for employees.name
     *
     * @mbg.generated 2023-05-06
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.age
     *
     * @return the value of employees.age
     *
     * @mbg.generated 2023-05-06
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.age
     *
     * @param age the value for employees.age
     *
     * @mbg.generated 2023-05-06
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.position
     *
     * @return the value of employees.position
     *
     * @mbg.generated 2023-05-06
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.position
     *
     * @param position the value for employees.position
     *
     * @mbg.generated 2023-05-06
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.hite_time
     *
     * @return the value of employees.hite_time
     *
     * @mbg.generated 2023-05-06
     */
    public Date getHiteTime() {
        return hiteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.hite_time
     *
     * @param hiteTime the value for employees.hite_time
     *
     * @mbg.generated 2023-05-06
     */
    public void setHiteTime(Date hiteTime) {
        this.hiteTime = hiteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employees.hire_time
     *
     * @return the value of employees.hire_time
     *
     * @mbg.generated 2023-05-06
     */
    public Date getHireTime() {
        return hireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employees.hire_time
     *
     * @param hireTime the value for employees.hire_time
     *
     * @mbg.generated 2023-05-06
     */
    public void setHireTime(Date hireTime) {
        this.hireTime = hireTime;
    }
}
